name: tmdb
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"
dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  keyboard_dismisser: ^3.0.0
  provider: ^6.1.1
  retrofit: ^4.1.0
  skeletonizer: ^1.0.1
  string_validator: ^1.0.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true
